server:
  port: 5001

zuul:
  ignoredServices: '*'
  routes:
    jalgo-arena-judge-pg: /judge/api/**
    jalgo-arena-problems-pg: /problems/api/**
    jalgo-arena-auth-pg: /auth/**
    jalgo-arena-submissions-pg: /submissions/api/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:5000/eureka/}
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: THREAD
          thread:
            timeoutInMilliseconds: 30000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
---
spring:
  profiles: heroku
eureka:
  instance:
    hostname: ${APP_NAME:jalogo-arena-api-pg}.herokuapp.com
    nonSecurePort: 80

logging:
  level:
    ROOT: INFO
    org.springframework.web: INFO
